### PR TITLE
Added a default color value when stop.color is undefined

### PR DESCRIPTION
**Pull request by dp901**

### CODE REVIEW

**Comment by BSick7** [comment]
Can you add some tests?

**Comment by BSick7** [comment]
Good work. I'm going to merge the tests, but move the color guard check into the `AddColorStop`.

**Comment by BSick7** [comment]
Manually merged.

**Comment by dp901** [comment]
OK Brad. Thanks.

**Comment by BSick7** [comment]
@dp901 All of your patches are released in 0.19.18.

**Pull request closed without merging**
